import React from 'react'
import { App } from '../App'
import store from '../Redux/Store'
import { Provider } from 'react-redux'
import LocalizationProvider from '@mui/lab/LocalizationProvider'
import AdapterDateFns from '@mui/lab/AdapterDateFns'
import { ThemeProvider } from '@mui/material/styles'
import { Container, useMediaQuery } from '@mui/material'
import { Box } from '@mui/system'
import { createDivaTheme } from '../lib/createDivaTheme'
import { Provider as Web3Provider } from '@web3-ui/hooks'
import { QueryClient, QueryClientProvider } from 'react-query'
import { projectId } from '../constants'
import Head from 'next/head'
import Markets from '../component/Markets/Markets'
import Header from '../component/Header/Header'

const queryClient = new QueryClient()

const WithProviders = () => {
  const prefersDarkMode = useMediaQuery('(prefers-color-scheme: dark)')

  const theme = React.useMemo(
    () => createDivaTheme(prefersDarkMode),
    [prefersDarkMode]
  )

  return (
    <Box
      sx={{
        background: theme.palette.background.default,
        color: theme.palette.text.secondary,
        fill: theme.palette.text.secondary,
        height: '100vh',
        left: 0,
        top: 0,
        width: '100%',
        display: 'flex',
        flexDirection: 'column',
        overflow: 'hidden',
      }}
    >
      <Web3Provider network={undefined as any} infuraId={projectId}>
        <QueryClientProvider client={queryClient}>
          <LocalizationProvider dateAdapter={AdapterDateFns}>
            <ThemeProvider theme={theme}>
              <Provider store={store}>
                <Header />
                <Container
                  disableGutters
                  sx={{ alignItems: 'left', height: '100%', overflow: 'auto' }}
                  maxWidth={false}
                >
                  <Markets />
                </Container>
              </Provider>
            </ThemeProvider>
          </LocalizationProvider>
        </QueryClientProvider>
      </Web3Provider>
    </Box>
  )
}

export default () => {
  return (
    <>
      <Head>
        <title>Diva Protocol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <WithProviders />
    </>
  )
}
