blank_issues_enabled: false
contact_links:
  - name: '💬 Diva discord community'
    url: https://discord.com/invite/e2gNcAWaZw
    about: Please join our discord community to stay up to date
      with the latest developments or get support
