import { Pool } from '../lib/queries'
export const Option: Pool = {
  cap: '',
  collateralBalanceLong: '',
  collateralBalanceLongInitial: '',
  collateralBalanceShort: '',
  collateralBalanceShortInitial: '',
  collateralToken: '',
  collateralSymbol: '',
  collateralTokenName: '',
  collateralDecimals: 0,
  dataFeedProvider: '',
  expiryDate: '',
  finalReferenceValue: '',
  floor: '',
  id: '',
  inflection: '',
  longToken: '',
  redemptionAmountLongToken: '',
  redemptionAmountShortToken: '',
  redemptionFee: '',
  referenceAsset: '',
  settlementFee: '',
  shortToken: '',
  statusFinalReferenceValue: '',
  statusTimeStamp: '',
  supplyLong: '',
  supplyLongInitial: '',
  supplyShort: '',
  supplyShortInitial: '',
}
