on:
  pull_request:
    paths:
      - packages/*-subgraph/**/*

name: Deploy Staging subgraph

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            **/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock', '**/package.json', 'yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Verify Node.js and Yarn Versions
        run: |
          node -v
          yarn -v

      - name: Authenticate with The Graph and Deploy
        env:
          THEGRAPH_ACCESS_TOKEN: ${{ secrets.THEGRAPH_ACCESS_TOKEN_TEST }}
        run: |
          yarn graph:auth
          yarn turbo run deploy-staging --scope="@diva/*-subgraph"
