on: push
#:
#    branches:
#      - main
name: Deploy the graph
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - run: yarn
      - name: Authenticate the graph and deploy
        env: 
          THEGRAPH_ACCESS_TOKEN: ${{ secrets.THEGRAPH_ACCESS_TOKEN_TEST }}
        run: yarn turbo run deploy --scope="@diva/*-subgraph"
