on: pull_request
name: Pull request automation
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install dependencies
        run: yarn

      - name: Run eslint and typescript to check for errors
        run: yarn lint

      - name: Run tests
        run: |
          export SECRET_WORDS="$TEST_WALLET_SECRET"
          yarn test:e2e
        env: 
          TESTWALLET_SECRET: ${{ secrets.TEST_WALLET_SECRET }}
