on: pull_request
name: Pull request automation
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        # with:
        #   ref: ${{ github.event.pull_request.head.ref }}

      - name: Run eslint
        run: yarn lint
