on:
  push:
    branches:
      - main
  pull_request:
    
name: Pull request automation
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
        
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Check Node.js and Yarn versions
        run: |
          node -v
          yarn -v

      - name: Install dependencies
        run: yarn

      - name: Run eslint and typescript to check for errors
        run: yarn lint

      # - name: Run tests
      #   run: yarn test
      #   env: 
      #     NETWORK_NAME: ropsten
      #     SECRET_WORDS: ${{ secrets.TEST_WALLET_SECRET }}
